In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [23]:
# sns provides  prebuild datasets
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [24]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [26]:
df.drop(['deck','embark_town','alive','class','who','adult_male'],axis=1,inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [28]:
df["age"].fillna(df["age"].mean(),inplace=True)

In [29]:
df["embarked"] = df["embarked"].mode()[0]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
columns = ['sex','embarked']
for col in columns:
    df[col]= le.fit_transform(df[col])

df['alone'] = df['alone'].astype(int)
df.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         0      0
1         1       1    0  38.0      1      0  71.2833         0      0
2         1       3    0  26.0      0      0   7.9250         0      1
3         1       1    0  35.0      1      0  53.1000         0      0
4         0       3    1  35.0      0      0   8.0500         0      1

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    int32  
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    int32  
 8   alone     891 non-null    int32  
dtypes: float64(2), int32(3), int64(4)
memory usage: 52.3 KB


In [33]:
X  = df.drop('survived',axis=1)
y = df['survived']

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [35]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [36]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [37]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

**Model Evaluation**

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [39]:
accuracy_score(y_test,y_pred)

0.7988826815642458

In [40]:
confusion_matrix(y_test,y_pred)

array([[90, 15],
       [21, 53]], dtype=int64)

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.86      0.83       105
           1       0.78      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179



**KNN Model**

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled,X_test_scaled

(array([[-1.61413602,  0.7243102 ,  1.22920747, ..., -0.07868358,
          0.        ,  0.81220297],
        [-0.40055118,  0.7243102 , -0.50350514, ..., -0.37714494,
          0.        ,  0.81220297],
        [ 0.81303367,  0.7243102 ,  0.18957991, ..., -0.47486697,
          0.        ,  0.81220297],
        ...,
        [ 0.81303367,  0.7243102 ,  0.88266495, ..., -0.35580399,
          0.        , -1.23121934],
        [-1.61413602, -1.38062393, -1.19659018, ...,  1.68320121,
          0.        , -1.23121934],
        [-1.61413602,  0.7243102 , -0.65752403, ...,  0.86074761,
          0.        , -1.23121934]]),
 array([[ 0.81303367,  0.7243102 ,  0.01239022, ..., -0.33390078,
          0.        , -1.23121934],
        [-0.40055118,  0.7243102 ,  0.11257046, ..., -0.42528387,
          0.        ,  0.81220297],
        [ 0.81303367,  0.7243102 , -0.73453348, ..., -0.47486697,
          0.        ,  0.81220297],
        ...,
        [ 0.81303367, -1.38062393,  0.6516366 , ..., -

In [43]:
from sklearn.neighbors import KNeighborsClassifier
knnmodel = KNeighborsClassifier(n_neighbors=5)
knnmodel.fit(X_train_scaled,y_train)
knnmodel

KNeighborsClassifier()

In [44]:
y_pred_knn = knnmodel.predict(X_test_scaled)

In [45]:
accuracy_score(y_test,y_pred_knn)

0.776536312849162

In [46]:
confusion_matrix(y_test,y_pred_knn)

array([[85, 20],
       [20, 54]], dtype=int64)

In [47]:
print("KNN Model Classification Report:")
print(classification_report(y_test,y_pred_knn))
print("-----------------------------------------------------------")
print("Logistic Regression Model Classification Report:")
print(classification_report(y_test,y_pred))

KNN Model Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       105
           1       0.73      0.73      0.73        74

    accuracy                           0.78       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

-----------------------------------------------------------
Logistic Regression Model Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.86      0.83       105
           1       0.78      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179



In [48]:
X_train

pclass  sex        age  sibsp  parch      fare  embarked  alone
331       1    1  45.500000      0      0   28.5000         0      1
733       2    1  23.000000      0      0   13.0000         0      1
382       3    1  32.000000      0      0    7.9250         0      1
704       3    1  26.000000      1      0    7.8542         0      0
813       3    0   6.000000      4      2   31.2750         0      0
..      ...  ...        ...    ...    ...       ...       ...    ...
106       3    0  21.000000      0      0    7.6500         0      1
270       1    1  29.699118      0      0   31.0000         0      1
860       3    1  41.000000      2      0   14.1083         0      0
435       1    0  14.000000      1      2  120.0000         0      0
102       1    1  21.000000      0      1   77.2875         0      0

[712 rows x 8 columns]

**Naive Bayes Theorem**

In [49]:
from sklearn.naive_bayes import GaussianNB
gnb  = GaussianNB()

gnb.fit(X_train,y_train)

GaussianNB()

In [50]:
y_pred_nb = gnb.predict(X_test)

In [51]:
accuracy_score(y_test,y_pred_nb)

0.7932960893854749

In [52]:
classification_report(y_test,y_pred_nb)

'              precision    recall  f1-score   support\n\n           0       0.83      0.82      0.82       105\n           1       0.75      0.76      0.75        74\n\n    accuracy                           0.79       179\n   macro avg       0.79      0.79      0.79       179\nweighted avg       0.79      0.79      0.79       179\n'

**Decision Tree**

In [53]:
from sklearn.tree import DecisionTreeClassifier
model_dtc = DecisionTreeClassifier(random_state=42)

In [54]:
model_dtc.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [55]:
y_pred_dtc = model_dtc.predict(X_test_scaled)

In [56]:
accuracy_score(y_test,y_pred_dtc)

0.7653631284916201

In [57]:
confusion_matrix(y_test,y_pred_dtc)

array([[83, 22],
       [20, 54]], dtype=int64)

In [58]:
print(classification_report(y_test,y_pred_dtc))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80       105
           1       0.71      0.73      0.72        74

    accuracy                           0.77       179
   macro avg       0.76      0.76      0.76       179
weighted avg       0.77      0.77      0.77       179



**Support Vector Machine (SVM)**

In [59]:
from sklearn.svm import SVC
svm_model = SVC(kernel="rbf")

In [60]:
svm_model.fit(X_train_scaled,y_train)

SVC()

In [61]:
y_pred_svm = svm_model.predict(X_test_scaled)

In [62]:
accuracy_score(y_test,y_pred_svm)

0.8100558659217877

In [63]:
confusion_matrix(y_test,y_pred_svm)

array([[92, 13],
       [21, 53]], dtype=int64)

In [64]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       105
           1       0.80      0.72      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179



**Cross Validation**

In [65]:
X = df.drop('survived',axis=1)
y = df['survived']

In [66]:
from sklearn.model_selection import cross_val_score


In [67]:
X_scaled = scaler.fit_transform(X)

In [76]:
svc_scores = cross_val_score(svm_model,X_scaled,y,cv=5, scoring='accuracy')
knn_scores = cross_val_score(knnmodel,X_scaled,y,cv=5, scoring='accuracy')

In [77]:
print("Cross Validation Score: ",svc_scores)
print("KNN Cross Validation Score: ", knn_scores)

Cross Validation Score:  [0.82681564 0.80898876 0.82022472 0.81460674 0.85955056]
KNN Cross Validation Score:  [0.7877095  0.78651685 0.8258427  0.83146067 0.83146067]


In [78]:
print(svc_scores.mean())
print("Cross Validation Score for SVM: ", svc_scores.mean())
print("Cross Validation Score for KNN: ", knn_scores.mean())

0.8260372857949909
Cross Validation Score for SVM:  0.8260372857949909
Cross Validation Score for KNN:  0.8125980792166217
